### PR TITLE
Disable 'send' button when list of recipients is empty

### LINKED ISSUE #330: Crash bij versturen van mails aan deelnemers activiteit
https://sentry.io/share/issue/ec6b615628f34341aca45ee24c28300c/

```
NoMethodError: undefined method `permit!' for nil:NilClass
  app/controllers/admin/participants_controller.rb:78:in `mail'
    render :json => Mailings::Participants.inform(@activity, params[:recipients].permit!.to_h.map { |id, item| item['email'] }, current_user.sender, params[:subject], params[:html]).deliver_later
...
(76 additional frame(s) were not displayed)

NoMethodError: undefined method `permit!' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by CrookedGrandma**
Closes #330 

Old issue but still relevant

### CODE REVIEW

**Review by fiinnnn — APPROVED** [review]
lgtm

**Comment by Mstiekema** [comment]
How do you reproduce the original error? I've tried a few things and I have not been able to do so.

**Comment by CrookedGrandma** [comment]
> How do you reproduce the original error? I've tried a few things and I have not been able to do so.

Set the amount people still have to pay to €0 in any activity, then send an email to the group of people that still need to pay. The list of recipients would be empty, but you could still send the email

**Review by Mstiekema — APPROVED** [review]
LGTM!

**Pull request merged**
