### PR TITLE
Activity summary views

### LINKED ISSUE #434: Export participants of activity
We thought it would be a useful to be able to export (to a simple .csv or similar) participants of an activity. Often we need a list of participants on paper for something during the activity (keep track of what drinks were bought, who is present etc.), sometimes we'd even like to simply export their e-mails so we can manually send mails or similar.

For this we'd like to be able to select what columns to export. Columns we thought of are `Naam`, `Reserve` (a boolean if the participant is on the spares list or not), `Prijs`, `Nog betalen` (a boolean if the participant still needs to pay or not), `Extra opmerking`, `E-mail`. With option to add empty columns with a custom name.

### PR DESCRIPTION
**Pull request by Raymonzut**
Closes #434

Introduces richer views for activity-participants

### CODE REVIEW

**Review by JustNireon — CHANGES_REQUESTED** [review]
Pressing show as csv twice adds extra lines to notes which is kinda weird. furthermore we yarn has a package that makes it real easy to add a "Copy to Clipboard" Button it would be a pretty nice feature to have aswell

**Comment by Raymonzut** [comment]
@JustNireon Alright, done, anything else for this feature?

**Comment by JustNireon** [comment]
Ill check copy to.clipboard this afternoon but otherwise lgtm

**Comment by JustNireon** [comment]
When pressing show as CSV when it's already summarized it still looks weird like this: 
image
Furthermore for copying to clipboard i would use the similar code used in '/app/assets/javascripts/admin' for consistency. 
`  (function () {
    new Clipboard("#copy_transactions .btn-clipboard");
  })();`

`      // Bind json data to copy button
      $("#copy_transactions button").attr(
        "data-clipboard-text",
        JSON.stringify(data)
      );`

**Review by JustNireon — APPROVED** [review]
LGTM

**Pull request merged**
