### PR TITLE
Update background for intro.svsticky.nl

### PR DESCRIPTION
**Pull request by TobiasDeBruijn**
The old one was due to be replaced.

### CODE REVIEW

**Review by SpookyBoy99 — CHANGES_REQUESTED** [review]
I agree that it needs a new background, however, I do think this one shows alcohol to prominently (ideally there would be no alcohol in the picture, but this limits your options severely).

Secondly, this picture has many people prominently showing their faces of which you have to ask consent before merging the pull request (if not given consent by all, either delete the branch or squash commits, so the image will no longer be publicly available). 

My suggestions for a background:
- https://fotos.svsticky.nl/introductie-2023---alms-&-bbq/c03569e0-8b0b-458a-97b8-f6fb4d5c8e54/
- https://fotos.svsticky.nl/introductie-2023---kamp/d02b3841-f651-4600-bf12-8bacd7050364/
- https://fotos.svsticky.nl/introductie-2023---usp-tour-&-walking-dinner/5929aa17-4e6a-43af-a556-00be44258199/
- https://fotos.svsticky.nl/introductie-2023---usp-tour-&-walking-dinner/ed9d6a86-6573-4908-88a7-a486a88ab022/

**Comment by TobiasDeBruijn** [comment]
Fair enough fair enough yeah. I like the 4th picture the most I think (https://fotos.svsticky.nl/introductie-2023---usp-tour-&-walking-dinner/ed9d6a86-6573-4908-88a7-a486a88ab022/) though I don't know the names of the two in front, so I cannot ask them for consent (help me out here :innocent: )

**Comment by SpookyBoy99** [comment]
The board is discussing which one they find most appropriate (number 4 is a high contender). Once the decision has been made, I will touch up the picture and make sure it fits on the website, acquire consent and submit it to you so you can commit it again. In the meantime, you can enable squashing for this repository, unless you want to do a manual rewrite of the history, which is something I thoroughly do not recommend.

**Comment by SilasPeters** [comment]
> I will see if I can propose another photo.

Perhaps my standards are too high, but I can't find any photo I believe best fits the intro website. During the next intro I will try to focus on such a picture.

Side note: [this picture](https://fotos.svsticky.nl/introductie-2023---kamp/df6caee9-f1a2-48ff-bc7c-34fabbe03867/) can be quite a funny alternative to [this picture](https://fotos.svsticky.nl/introductie-2023---kamp/d02b3841-f651-4600-bf12-8bacd7050364/), for it shows some chaos and thus some character: Sticky is not just an association, it's welcoming and casual.

**Comment by TobiasDeBruijn** [comment]
> The board is discussing which one they find most appropriate (number 4 is a high contender)

Should I also throw up a ball with KB18?

**Comment by SpookyBoy99** [comment]
> Should I also throw up a ball with KB18?

Of course

**Comment by SilasPeters** [comment]
If I were to choose between said options, I would also choose the [fourth option.](https://production-svsticky-photos.ams3.cdn.digitaloceanspaces.com/ed9d6a86-6573-4908-88a7-a486a88ab022_w_1600.jpg)

**Comment by SpookyBoy99** [comment]
Number four has been chosen by the majority of the current and candidate board + Silas and consent has been given by all parties in the picture, so we are good to go

**Review by SilasPeters — CHANGES_REQUESTED** [review]
Let me see if I can make the picture less yellow. Other than that, I am really looking forward to seeing the photo in production! ❤️

**Comment by SpookyBoy99** [comment]
I would advise against that, if you look at #1114 you can see the yellow has been incorporated in the website design, giving it a warmer appearance and nice homogenous feel

**Comment by SilasPeters** [comment]
🤔 time to review it then

**Review by SpookyBoy99 — APPROVED** [review]

**Comment by SilasPeters** [comment]
> Perhaps my standards are too high, but I can't find any photo I believe best fits the intro website

Oh wow, seeing the new photo in action makes me realize I love the change!

**Review by SilasPeters — APPROVED** [review]
\*Happy approve\*

**Comment by TobiasDeBruijn** [comment]
💛

**Pull request merged**
