### PR TITLE
Update to Mollie v2 API: Part 2 electric boogaloo

### PR DESCRIPTION
**Pull request by leuke-naam**
Fixes issues with #1133

### CODE REVIEW

**Review by TobiasDeBruijn — DISMISSED** [review]

**Review by SilasPeters — APPROVED** [review]
Lgtm

**Comment by SilasPeters** [comment]
@leuke-naam and @TobiasDeBruijn I pulled a big brain and tested this branch on staging _without_ merging, by simply checking out this branch and restarting koala :brain: . Everything seems to work! Two things though:

1. If the payment is left as 'open', the user is not notified, but I believe @leuke-naam showed me once that a blue banner displaying 'your payment is being processed' should pop up. If that's true, that did not work.
2. The payments are in test mode, but I assume this is toggled off when a different `MOLLIE_TOKEN` is used in `.env` in production.

**Review by TobiasDeBruijn — APPROVED** [review]

**Comment by leuke-naam** [comment]
> @leuke-naam and @TobiasDeBruijn I pulled a big brain and tested this branch on staging _without_ merging, by simply checking out this branch and restarting koala 🧠 . Everything seems to work! Two things though:
> 
> 1. If the payment is left as 'open', the user is not notified, but I believe @leuke-naam showed me once that a blue banner displaying 'your payment is being processed' should pop up. If that's true, that did not work.
> 2. The payments are in test mode, but I assume this is toggled off when a different `MOLLIE_TOKEN` is used in `.env` in production.

1. Payment status `open` is not applicable for iDeal payments, if in the future we were to accept more payment types we could handle this status
2. Correct

**Comment by SilasPeters** [comment]
Then everything works! Somehow GitHub complains some requirements for merging are not met, so I will admin abuse

**Pull request merged**
