### PR TITLE
Update to Mollie v2 API

### LINKED ISSUE #1130: Mollie API deprecation
From an email from Mollie:
```

Ondersteuning voor Mollie API V1 is in juli 2023 beëindigd. Deze versie van de API zal volledig worden uitgeschakeld op 31 december 2024.

Uit onze gegevens blijkt dat je de afgelopen 7 dagen betalingen hebt verwerkt via de V1 API. Om ervoor te zorgen dat je betalingen kan blijven ontvangen, raden we je aan om zo snel mogelijk over te stappen naar onze nieuwste API, Mollie API V2.

Wat moet ik doen?
Als je een platform of plug-in van een derde partij gebruikt om betaling bij Mollie aan te maken, zorg er dan voor dat je de nieuwste versie hebt geïnstalleerd. Als die versie Mollie API V2 niet ondersteunt, dien je contact op te nemen met de leverancier van het platform.
```
The v1 API (Which we use) goes EOL on december 31st of this year. We need to switch to v2 (or v3 if it exists) before that date

### PR DESCRIPTION
**Pull request by leuke-naam**
Closes #1130

### CODE REVIEW

**Review by SilasPeters — COMMENTED** [review]
I have not tested it, but damn these changes seem sleek

**Comment by stickyPiston** [comment]
I've checked out the changes, but it seems that failed transactions just cause the payment to be restarted. Moreover, the ideal provider button on the payment page in koala doesn't seem to have any effect anymore since it now seems to be included in mollie. Are these issues with the setup i'm testing with or are these implementation errors?

**Comment by leuke-naam** [comment]
> @leuke-naam could you elaborate?

No

**Comment by SilasPeters** [comment]
@leuke-naam I tried to fix the security issue stopping us from deploying, but when testing I get an `401 Unauthorized Request` error (`Mollie::RequestError in Members::PaymentsController#pay_activities`). I assume this is because I am running this from localhost?

Anyway, could you check my latest changes? I am not sure if they work.

**Review by SilasPeters — APPROVED** [review]

**Comment by TobiasDeBruijn** [comment]
> @leuke-naam I tried to fix the security issue stopping us from deploying, but when testing I get an `401 Unauthorized Request` error (`Mollie::RequestError in Members::PaymentsController#pay_activities`). I assume this is because I am running this from localhost?
> 
> Anyway, could you check my latest changes? I am not sure if they work.

@SilasPeters Were you able to solve this?

**Comment by SilasPeters** [comment]
No, but @leuke-naam said "looks good, seems to work"

**Comment by TobiasDeBruijn** [comment]
Right. @leuke-naam How did you get it to work locally? I haven't had the time to test it out myself, but would like to have it documented for the future.

**Comment by SilasPeters** [comment]
https://www.youtube.com/watch?v=m3zvVGJrTP8

**Comment by TobiasDeBruijn** [comment]
I don't entirely agree with this merge. We still have not got an answer to the question above.

**Comment by SilasPeters** [comment]
@TobiasDeBruijn granted, I should have discussed. My philosophy was 'we need to test it on dev anyway'. Also, the solution to the 401 error was using ngrok, and testing on dev was basically that. 

Again, should have discussed, but no time for caution

**Comment by SilasPeters** [comment]
@leuke-naam @TobiasDeBruijn on dev.svsticky.nl, clicking on pay does not do anything but redirecting to `https://koala.dev.svsticky.nl/`. Furthermore, somehow all media does not load... Might have to do with me accidentally doing `git clean -fdx` on the server, but removing everything and redeploying does not fix

**Comment by TobiasDeBruijn** [comment]
> @TobiasDeBruijn granted, I should have discussed. My philosophy was 'we need to test it on dev anyway'. Also, the solution to the 401 error was using ngrok, and testing on dev was basically that.
> 
> Again, should have discussed, but no time for caution

Neat! Could you document the steps to set up ngrok? Then I'm all happy :smile:

**Comment by stickyPiston** [comment]
It's good that you mention it! These steps will also need to be documented in undead-mongoose, now that we use mollie there too, and django requires some additional setup to work with ngrok.

**Comment by SilasPeters** [comment]
I don't know any concrete steps, nor have I done it. I just remember sem mentioning he needs ngrok to make it work, and I figured the 401 error is because Mollie does not authenticate localhost urls

**Pull request merged**
