### PR TITLE
pin node2nix and update generated files

### LINKED ISSUE #877: Nix warns that stdenv.lib is deprecated
> trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938

Easy fix probably

### PR DESCRIPTION
**Pull request by Riscky**
Closes #877 by pinning the latest version of node2nix that generates files with direct lib calls

### CODE REVIEW

**Comment by Riscky** [comment]
As we are changing the branching of Koala (/svsticky/sadserver/issues/323), please change this PR to merge to master instead of development

**Comment by Riscky** [comment]
This will be superseded by #897 and can be closed if that is merged

**Comment by Riscky** [comment]
> This will be superseded by #897 and can be closed if that is merged

This is not true in retrospect, but I'll have to make some changes to get this mergable

**Comment by Riscky** [comment]
This is ready for review again :)

**Review by JustNireon — APPROVED** [review]
LGTM :)

**Pull request merged**
