### PR TITLE
[Release] 2.7

### PR DESCRIPTION
**Pull request by Mstiekema**
# 2.7 Release
This is a big one! Lots of bug fixes (aka MailChimp will work some day...), new features and een hele hoop nix. Thanks to everyone for contributing to this release! @Riscky @JustNireon @fiinnnn @CrookedGrandma @maartenberg @Mstiekema. 

### Changes
- Nix is now in place to help us build koala more easily.
- Cachix is implemented to help with build times.
- Fixed some bugs regarding the magnificent-sloth integration.
- Updated welcome mail regarding the Sticky WhatsApp.
- Fixed multiple issues regarding changing your email address and updating preferences in MailChimp.
- Fixed translations regarding flash messages.

This PR also includes changes for v2.6.3 due to some fucky wucky with git. To see the changes for that release, please check #758

### CODE REVIEW

**Comment by Mstiekema** [comment]
Waiting for atleast #776 to be merged & have to fix development before this. For now not permitted to force push to fix :( 
image

**Comment by Mstiekema** [comment]
Tested on staging and it seems to work just fine!

**Comment by Mstiekema** [comment]
Okay so the rebase fucked the history again...

**Comment by CrookedGrandma** [comment]
And that's why we use merges instead of rebases

**Pull request merged**
